package connections;

/**
 * The Response class represents a data structure that encapsulates the details
 * of a response generated by a command in the application. It includes information
 * about the command ID, the type of response, the print style, the content, and an optional prompt.
 */
public class Response {

    /**
     * The unique identifier of the command associated with this response.
     */
    private int commandId;

    /**
     * The type of the response, represented by the {@link ResponseType} enum.
     */
    private ResponseType type;

    /**
     * The print style of the response, defined by the {@link PrintType} enum.
     */
    private PrintType printType;

    /**
     * The content of the response, providing details or messages related to the command.
     * If the content is null or empty, the print type defaults to {@link PrintType#NONE}.
     */
    private String content;

    /**
     * An optional prompt providing additional instructions or data for subsequent user input.
     * If the prompt is empty, it defaults to null.
     */
    private String prompt;


    /**
     * Constructs a new Response object with the specified parameters.
     *
     * @param commandId The unique identifier of the command.
     * @param type      The type of the response.
     * @param printType The print style of the response.
     * @param content   The content of the response.
     * @param prompt    An optional prompt for the user (nullable).
     */
    public Response(int commandId, ResponseType type, PrintType printType, String content, String prompt) {
        this.commandId = commandId;
        this.type = type;
        this.printType = printType;
        this.content = (content != null && content.equals("")) ? null : content;
        if (this.content == null) this.printType = PrintType.NONE;
        this.prompt = prompt.equals("") ? null : prompt;
    }

    /**
     * Constructs a new Response object without a prompt.
     *
     * @param commandId The unique identifier of the command.
     * @param type      The type of the response.
     * @param printType The print style of the response.
     * @param content   The content of the response.
     */
    public Response(int commandId, ResponseType type, PrintType printType, String content) {
        this(commandId, type, printType, content, "");
    }


    /**
     * Retrieves the command ID associated with this response.
     *
     * @return The command ID.
     */
    public int getCommandId() {
        return commandId;
    }

    /**
     * Retrieves the type of the response.
     *
     * @return The {@link ResponseType} of the response.
     */
    public ResponseType getType() {
        return type;
    }

    /**
     * Retrieves the print style of the response.
     *
     * @return The {@link PrintType} of the response.
     */
    public PrintType getPrintType() {
        return printType;
    }

    /**
     * Retrieves the content of the response.
     *
     * @return The content of the response as a string.
     */
    public String getContent() {
        return content;
    }

    /**
     * Retrieves the optional prompt associated with the response.
     *
     * @return The prompt as a string, or null if no prompt is set.
     */
    public String getPrompt() {
        return prompt;
    }
}
