package commands;

import connections.PrintType;
import connections.Request;
import connections.RequestType;
import connections.Response;
import connections.ResponseType;
import connections.ServerRequest;
import connections.ServerResponse;
import controls.CollectionControl;
import controls.CommandControl;
import controls.flat_builder.FlatBuilderAdd;
import models.Flat;
import util.StringWrapper;

/**
 * The Add class implements the {@link ICommand} interface and facilitates the addition of a new flat
 * to the collection. It utilizes a builder pattern to collect the required values for creating a
 * {@link Flat} instance. Once all the values are provided, the flat is added to the collection.
 */
public class Add implements ICommand{

    /**
     * The unique identifier of the command.
     */
    private int id;

    /**
     * The {@link CommandControl} instance for managing command-related operations.
     */
    private CommandControl commandControl;

    /**
     * The {@link CollectionControl} instance for managing the collection.
     */
    private CollectionControl collectionControl;

    /**
     * The last {@link Response} generated by this command.
     */
    private Response lastResponse;

    /**
     * The {@link FlatBuilderAdd} instance responsible for constructing a {@link Flat} object.
     */
    private FlatBuilderAdd builder;

    /**
     * Constructs a new Add command.
     *
     * @param id               The unique identifier of the command.
     * @param arguments        The initial arguments provided for the command.
     * @param commandControl   The {@link CommandControl} instance for managing commands.
     * @param collectionControl The {@link CollectionControl} instance for managing the collection.
     */
    public Add(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl) {
        super();
        
        this.id = id;
        this.commandControl = commandControl;
        this.collectionControl = collectionControl;
        builder = new FlatBuilderAdd(collectionControl);
        proceedRequest(new Request(id, RequestType.EXECUTE_COMMAND, arguments));
    }


    /**
     * Returns the unique identifier of the command.
     *
     * @return The command ID.
     */
    public int getId() {
        return id;
    }

     /**
     * Returns the {@link CommandControl} instance associated with this command.
     *
     * @return The {@link CommandControl} instance.
     */
    public CommandControl getCommandControl() {
        return commandControl;
    }

    /**
     * Returns the {@link CollectionControl} instance associated with this command.
     *
     * @return The {@link CollectionControl} instance.
     */
    public CollectionControl getCollectionControl() {
        return collectionControl;
    }

    /**
     * Returns the last {@link Response} generated by this command.
     *
     * @return The last {@link Response}.
     */
    public Response getLastResponse() {
        return lastResponse;
    }


    /**
     * Executes the command based on the provided {@link Request}.
     * Handles the addition of a new flat by collecting required values using the builder.
     *
     * @param request The {@link Request} object containing the command details.
     * @return A {@link Response} object representing the result of the command execution.
     */
    private Response executeCommand(Request request) {
        if (request instanceof ServerRequest) {
            ServerRequest req = (ServerRequest) request;
            builder = (FlatBuilderAdd) req.getContentExt();
            builder.setCollection(collectionControl);
            Flat flat = builder.build();
            if (collectionControl.add(flat, req.getUser().getName())) return new ServerResponse(req.getClientCommandId(), ResponseType.SUCCESS, PrintType.LINE, flat, req.getClientId());
            else return new ServerResponse(req.getClientCommandId(), ResponseType.VALIDATION_FAILURE, PrintType.LINE, new StringWrapper(""), req.getClientId());
        }

        if (request.getType() == RequestType.EXECUTE_COMMAND) {
            return new Response(getId(), ResponseType.REQUEST_VALUES, PrintType.LINE, "Начало добавления квартиры", builder.getPrompt());
        }
        
        Response resp = builder.setValue(request.getContent());
        String prompt = builder.getPrompt();
        if (resp.getType() == ResponseType.SUCCESS) {
            if (prompt != null) return new Response(getId(), ResponseType.REQUEST_VALUES, PrintType.NONE, resp.getContent(), prompt);
            else {
                Flat flat = builder.build();
                if (collectionControl.add(flat, "ADMIN")) return new Response(getId(), ResponseType.SUCCESS, PrintType.LINE, "Квартира успешно добавлена:\n" + flat.toString());
                else return new Response(getId(), ResponseType.VALIDATION_FAILURE, PrintType.LINE, "Не удалось добавить квартиру");
            }
        }
        return new Response(getId(), resp.getType(), resp.getPrintType(), resp.getContent(), prompt);
    }

    
    /**
     * Processes the provided request and delegates it to the appropriate command handler.
     *
     * @param request The {@link Request} to be processed.
     * @return A {@link Response} object representing the result of the request processing.
     */
    @Override
    public Response proceedRequest(Request request) {
        if (request.getType() == RequestType.EXECUTE_COMMAND || request.getType() == RequestType.PROCEED_COMMAND) {
            lastResponse = executeCommand(request);
            return lastResponse;
        }

        return new Response(getId(), ResponseType.SUCCESS, PrintType.WARNING, "Not correct request type");
    }


    /**
     * The Factory class is responsible for creating instances of the Add command and providing
     * descriptions of its functionality.
     */
    public static class Factory implements ICommandFactory {
       
        /**
         * Creates a new instance of the Add command.
         *
         * @param id               The unique identifier of the command.
         * @param arguments        The initial arguments provided for the command.
         * @param commandControl   The {@link CommandControl} instance for managing commands.
         * @param collectionControl The {@link CollectionControl} instance for managing the collection.
         * @return A new instance of the Add command.
         */
        @Override
        public ICommand create(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl, Request request) {
            return new Add(id, arguments, commandControl, collectionControl);
        }

        /**
         * Returns a brief description of the Add command.
         *
         * @return A short description of the command.
         */
        @Override
        public String getDescription() {
            return "add {flat}: добавить новую квартиру в коллекцию";
        }

        /**
         * Returns an extended description of the Add command, detailing the input requirements.
         *
         * @return A detailed description of the command.
         */
        @Override
        public String getExtendedDescription() {
            return "add {flat}: добавить новую квартиру в коллекцию.\nНеобходимые значения для flat будут запрошены в последующих строчках.";
        }
    }
}
