package commands;

import connections.PrintType;
import connections.Request;
import connections.RequestType;
import connections.Response;
import connections.ResponseType;
import connections.ServerRequest;
import connections.ServerResponse;
import controls.CollectionControl;
import controls.CommandControl;
import util.StringWrapper;

/**
 * The Clear class implements the {@link ICommand} interface and provides functionality
 * to clear all elements from the collection. It ensures that the collection is emptied
 * and confirms the operation with a success response.
 */
public class Clear implements ICommand{

    /**
     * The unique identifier of the command.
     */
    private int id;

    /**
     * The {@link CommandControl} instance for managing command-related operations.
     */
    private CommandControl commandControl;

    /**
     * The {@link CollectionControl} instance for managing the collection of elements.
     */
    private CollectionControl collectionControl;

    /**
     * The last {@link Response} generated during the command execution.
     */
    private Response lastResponse;

    /**
     * Constructs a new Clear command.
     *
     * @param id               The unique identifier for this command.
     * @param arguments        The initial arguments provided to the command (not used).
     * @param commandControl   The {@link CommandControl} instance for managing commands.
     * @param collectionControl The {@link CollectionControl} instance for managing the collection.
     */
    public Clear(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl, Request request) {
        super();
        
        this.id = id;
        this.commandControl = commandControl;
        this.collectionControl = collectionControl;
        proceedRequest(request);
    }


    /**
     * Returns the unique identifier of the command.
     *
     * @return The command ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the {@link CommandControl} instance associated with this command.
     *
     * @return The {@link CommandControl} instance.
     */
    public CommandControl getCommandControl() {
        return commandControl;
    }

    /**
     * Returns the {@link CollectionControl} instance associated with this command.
     *
     * @return The {@link CollectionControl} instance.
     */
    public CollectionControl getCollectionControl() {
        return collectionControl;
    }

    /**
     * Returns the last {@link Response} generated by this command.
     *
     * @return The last {@link Response}.
     */
    public Response getLastResponse() {
        return lastResponse;
    }


    /**
     * Executes the command to clear the collection and returns a success response.
     *
     * @param request The {@link Request} object containing the command details.
     * @return A {@link Response} confirming that the collection has been successfully cleared.
     */
    private Response executeCommand(Request request) {
        if (request instanceof ServerRequest) {
            ServerRequest req = (ServerRequest) request;
            collectionControl.clear(req.getUser().getName());

            return new ServerResponse(req.getClientCommandId(), ResponseType.SUCCESS, PrintType.LINE, new StringWrapper("no_data"), req.getClientId());
        }
        collectionControl.clear("ADMIN");
        return new Response(getId(), ResponseType.SUCCESS, PrintType.LINE, "Коллекция успешно очищена.");
    }

    /**
     * Processes the provided request and delegates it to the appropriate command handler.
     *
     * @param request The {@link Request} to be processed.
     * @return A {@link Response} representing the outcome of the request processing.
     */
    @Override
    public Response proceedRequest(Request request) {
        if (request.getType() == RequestType.EXECUTE_COMMAND) {
            lastResponse = executeCommand(request);
            return lastResponse;
        }

        return new Response(getId(), ResponseType.SUCCESS, PrintType.WARNING, "Not correct request type");
    }


    /**
     * The Factory class provides methods to create instances of the Clear command
     * and describe its functionality.
     */
    public static class Factory implements ICommandFactory {

        /**
         * Creates a new instance of the Clear command.
         *
         * @param id               The unique identifier for the command.
         * @param arguments        The initial arguments provided to the command (not used).
         * @param commandControl   The {@link CommandControl} instance for managing commands.
         * @param collectionControl The {@link CollectionControl} instance for managing the collection.
         * @return A new instance of the Clear command.
         */
        @Override
        public ICommand create(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl, Request request) {
            return new Clear(id, arguments, commandControl, collectionControl, request);
        }

        /**
         * Returns a brief description of the Clear command.
         *
         * @return A short description of the command functionality.
         */
        @Override
        public String getDescription() {
            return "clear: очистить коллекцию";
        }

        /**
         * Returns an extended description of the Clear command.
         *
         * @return A detailed description of the command functionality.
         */
        @Override
        public String getExtendedDescription() {
            return "clear: очистить коллекцию.";
        }
    }
}
