package commands;

import connections.PrintType;
import connections.Request;
import connections.RequestType;
import connections.Response;
import connections.ResponseType;
import controls.CollectionControl;
import controls.CommandControl;

/**
 * The ExecuteScript class implements the {@link ICommand} interface and provides functionality
 * to execute a script from a specified file. This command reads the commands from the file
 * and processes them sequentially.
 */
public class ExecuteScript implements ICommand{

    /**
     * The unique identifier of the command.
     */
    private int id;

    /**
     * The {@link CommandControl} instance for managing command-related operations.
     */
    private CommandControl commandControl;

    /**
     * The {@link CollectionControl} instance for managing the collection of elements.
     */
    private CollectionControl collectionControl;

    /**
     * The last {@link Response} generated during the command execution.
     */
    private Response lastResponse;


    /**
     * Constructs a new ExecuteScript command.
     *
     * @param id               The unique identifier for this command.
     * @param arguments        The initial arguments provided to the command, typically the file name.
     * @param commandControl   The {@link CommandControl} instance for managing commands.
     * @param collectionControl The {@link CollectionControl} instance for managing the collection.
     */
    public ExecuteScript(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl) {
        super();
        
        this.id = id;
        this.commandControl = commandControl;
        this.collectionControl = collectionControl;
        proceedRequest(new Request(id, RequestType.EXECUTE_COMMAND, arguments));
    }


    /**
     * Returns the unique identifier of the command.
     *
     * @return The command ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the {@link CommandControl} instance associated with this command.
     *
     * @return The {@link CommandControl} instance.
     */
    public CommandControl getCommandControl() {
        return commandControl;
    }

    /**
     * Returns the {@link CollectionControl} instance associated with this command.
     *
     * @return The {@link CollectionControl} instance.
     */
    public CollectionControl getCollectionControl() {
        return collectionControl;
    }

    /**
     * Returns the last {@link Response} generated by this command.
     *
     * @return The last {@link Response}.
     */
    public Response getLastResponse() {
        return lastResponse;
    }


    /**
     * Executes the command based on the provided {@link Request}.
     * Validates the file name argument and initiates the script execution.
     *
     * @param request The {@link Request} object containing the command details.
     * @return A {@link Response} indicating whether the script was opened or closed, or an error if no file name was provided.
     */
    private Response executeCommand(Request request) {
        if (request.getType() == RequestType.EXECUTE_COMMAND) {
            if (request.getContent() == null) return new Response(getId(), ResponseType.INVALID_ARGUMENT, PrintType.ERROR, "Команда execute_script в обязательном порядке принимает аргумент file_name.\nЧто бы узнать про команды подробнее, введите help.");
            return new Response(getId(), ResponseType.OPEN_SCRIPT, PrintType.NONE, request.getContent());
        }
        
        return new Response(getId(), ResponseType.CLOSE_SCRIPT, PrintType.LINE, request.getContent());
    }

    /**
     * Processes the provided request and delegates it to the appropriate command handler.
     *
     * @param request The {@link Request} to be processed.
     * @return A {@link Response} representing the outcome of the request processing.
     */
    @Override
    public Response proceedRequest(Request request) {
        if (request.getType() == RequestType.EXECUTE_COMMAND || request.getType() == RequestType.PROCEED_COMMAND) {
            lastResponse = executeCommand(request);
            return lastResponse;
        }

        return new Response(getId(), ResponseType.SUCCESS, PrintType.WARNING, "Not correct request type");
    }


    /**
     * The Factory class provides methods to create instances of the ExecuteScript command
     * and describe its functionality.
     */
    public static class Factory implements ICommandFactory {

        /**
         * Creates a new instance of the ExecuteScript command.
         *
         * @param id               The unique identifier for the command.
         * @param arguments        The initial arguments provided to the command, typically the file name.
         * @param commandControl   The {@link CommandControl} instance for managing commands.
         * @param collectionControl The {@link CollectionControl} instance for managing the collection.
         * @return A new instance of the ExecuteScript command.
         */
        @Override
        public ICommand create(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl, Request request) {
            return new ExecuteScript(id, arguments, commandControl, collectionControl);
        }

        /**
         * Returns a brief description of the ExecuteScript command.
         *
         * @return A short description of the command functionality.
         */
        @Override
        public String getDescription() {
            return "execute_script file_name: выполнить скрипт, расположенный в file_name";
        }

        /**
         * Returns an extended description of the ExecuteScript command, detailing its requirements.
         *
         * @return A detailed description of the command functionality.
         */
        @Override
        public String getExtendedDescription() {
            return "execute_script file_name: выполнить скрипт, расположенный в file_name.";
        }
    }
}
