package commands;

import connections.PrintType;
import connections.Request;
import connections.RequestType;
import connections.Response;
import connections.ResponseType;
import connections.ServerRequest;
import connections.ServerResponse;
import controls.CollectionControl;
import controls.CommandControl;
import models.Flat;
import util.LongWrapper;
import util.StringWrapper;


/**
 * The Exit class implements the {@link ICommand} interface and provides functionality 
 * to terminate the program execution without saving data to a file.
 */
public class GetById implements ICommand{

    /**
     * The unique identifier of the command.
     */
    private int id;

    /**
     * The {@link CommandControl} instance for managing command-related operations.
     */
    private CommandControl commandControl;

    /**
     * The {@link CollectionControl} instance for managing the collection (unused in this command).
     */
    private CollectionControl collectionControl;

    /**
     * The last {@link Response} generated during the command execution.
     */
    private Response lastResponse;


    /**
     * Constructs a new Exit command.
     *
     * @param id               The unique identifier for this command.
     * @param arguments        The initial arguments provided to the command (unused).
     * @param commandControl   The {@link CommandControl} instance for managing commands.
     * @param collectionControl The {@link CollectionControl} instance for managing the collection.
     */
    public GetById(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl) {
        super();
        
        this.id = id;
        this.commandControl = commandControl;
        this.collectionControl = collectionControl;
        proceedRequest(new Request(id, RequestType.EXECUTE_COMMAND, arguments));
    }


    /**
     * Returns the unique identifier of the command.
     *
     * @return The command ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the {@link CommandControl} instance associated with this command.
     *
     * @return The {@link CommandControl} instance.
     */
    public CommandControl getCommandControl() {
        return commandControl;
    }

    /**
     * Returns the {@link CollectionControl} instance associated with this command.
     *
     * @return The {@link CollectionControl} instance.
     */
    public CollectionControl getCollectionControl() {
        return collectionControl;
    }

    /**
     * Returns the last {@link Response} generated by this command.
     *
     * @return The last {@link Response}.
     */
    public Response getLastResponse() {
        return lastResponse;
    }


    /**
     * Executes the command by returning a response indicating program termination.
     *
     * @param request The {@link Request} object containing the command details.
     * @return A {@link Response} indicating that the program should exit.
     */
    private Response executeCommand(Request request) {
        if (request instanceof ServerRequest) {
            ServerRequest req = (ServerRequest) request;
            try {
                // Long id =  ArgumentTypeConverter.getLong(request.getContent())
                Long id = ((LongWrapper) req.getContentExt()).getValue();
                Flat flat = collectionControl.getById(id);
                if (flat == null) return new ServerResponse(req.getClientCommandId(), ResponseType.INVALID_ARGUMENT, PrintType.ERROR, new StringWrapper("no_data"), req.getClientId());
                return new ServerResponse(req.getClientCommandId(), ResponseType.SUCCESS, PrintType.LINE, flat, req.getClientId());
            }
            catch (NumberFormatException e) {
                return new ServerResponse(req.getClientCommandId(), ResponseType.INVALID_ARGUMENT, PrintType.ERROR, new StringWrapper("Неверный формат id"), req.getClientId());
            }
        }
        return new Response(getId(), ResponseType.INVALID_COMMAND, PrintType.ERROR, "Эта команда не доступна");
    }

    /**
     * Processes the provided request and delegates it to the appropriate command handler.
     *
     * @param request The {@link Request} to be processed.
     * @return A {@link Response} representing the outcome of the request processing.
     */
    @Override
    public Response proceedRequest(Request request) {
        if (request.getType() == RequestType.EXECUTE_COMMAND) {
            lastResponse = executeCommand(request);
            return lastResponse;
        }

        return new Response(getId(), ResponseType.SUCCESS, PrintType.WARNING, "Not correct request type");
    }


    /**
     * The Factory class provides methods to create instances of the Exit command 
     * and describe its functionality.
     */
    public static class Factory implements ICommandFactory {

        /**
         * Creates a new instance of the Exit command.
         *
         * @param id               The unique identifier for the command.
         * @param arguments        The initial arguments provided to the command (unused).
         * @param commandControl   The {@link CommandControl} instance for managing commands.
         * @param collectionControl The {@link CollectionControl} instance for managing the collection.
         * @return A new instance of the Exit command.
         */
        @Override
        public ICommand create(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl, Request request) {
            return new GetById(id, arguments, commandControl, collectionControl);
        }

        /**
         * Returns a brief description of the Exit command.
         *
         * @return A short description of the command functionality.
         */
        @Override
        public String getDescription() {
            return "";
        }

        /**
         * Returns an extended description of the Exit command.
         *
         * @return A detailed description of the command functionality.
         */
        @Override
        public String getExtendedDescription() {
            return "";
        }
    }
}
