package commands;

import java.time.LocalDateTime;

import connections.PrintType;
import connections.Request;
import connections.RequestType;
import connections.Response;
import connections.ResponseType;
import connections.ServerRequest;
import connections.ServerResponse;
import controls.CollectionControl;
import controls.CommandControl;
import util.InfoWrapper;

/**
 * The Info class implements the {@link ICommand} interface and provides functionality
 * to display detailed information about the collection, such as its type, size, 
 * initialization time, and the last save time.
 */
public class Info implements ICommand{

    /**
     * The unique identifier of the command.
     */
    private int id;

    /**
     * The {@link CommandControl} instance for managing command-related operations.
     */
    private CommandControl commandControl;

    /**
     * The {@link CollectionControl} instance for managing the collection of elements.
     */
    private CollectionControl collectionControl;

    /**
     * The last {@link Response} generated during the command execution.
     */
    private Response lastResponse;


    /**
     * Constructs a new Info command.
     *
     * @param id               The unique identifier for this command.
     * @param arguments        The initial arguments provided to the command (not used).
     * @param commandControl   The {@link CommandControl} instance for managing commands.
     * @param collectionControl The {@link CollectionControl} instance for managing the collection.
     */
    public Info(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl) {
        super();
        
        this.id = id;
        this.commandControl = commandControl;
        this.collectionControl = collectionControl;
        proceedRequest(new Request(id, RequestType.EXECUTE_COMMAND, arguments));
    }


    /**
     * Returns the unique identifier of the command.
     *
     * @return The command ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the {@link CommandControl} instance associated with this command.
     *
     * @return The {@link CommandControl} instance.
     */
    public CommandControl getCommandControl() {
        return commandControl;
    }

    /**
     * Returns the {@link CollectionControl} instance associated with this command.
     *
     * @return The {@link CollectionControl} instance.
     */
    public CollectionControl getCollectionControl() {
        return collectionControl;
    }

    /**
     * Returns the last {@link Response} generated by this command.
     *
     * @return The last {@link Response}.
     */
    public Response getLastResponse() {
        return lastResponse;
    }


    /**
     * Executes the command by generating a detailed summary of the collection's state,
     * including its type, size, initialization time, and last save time.
     *
     * @param request The {@link Request} object containing the command details.
     * @return A {@link Response} object with the generated information.
     */
    private Response executeCommand(Request request) {
        
        String result = "Информация о коллекции:\n";
        
        LocalDateTime lastSaveTime = getCollectionControl().getLastSaveTime();
		String lastSaveTimeString = (lastSaveTime == null) ? "в данной сессии сохранения еще не происходило" :
		lastSaveTime.toLocalDate().toString() + " " + lastSaveTime.toLocalTime().toString();
        
        LocalDateTime initTime = getCollectionControl().getInitTime();
        String initTimeString = initTime.toLocalDate().toString() + " " + initTime.toLocalTime().toString();
        
        
        if (request instanceof ServerRequest) {
            ServerRequest req = (ServerRequest) request;
            return new ServerResponse(req.getClientCommandId(), ResponseType.SUCCESS, PrintType.LINE, new InfoWrapper(
                getCollectionControl().getCollection().getClass().toString(),
                getCollectionControl().getCollection().size(),
                initTime,
                lastSaveTime
            ), req.getClientId());
        }

        result += "Тип: " + getCollectionControl().getCollection().getClass().toString() + "\n";
        result += "Количество элементов: " + getCollectionControl().getCollection().size() + "\n";
        result += "Дата инициализации: " + initTimeString + "\n";
        result += "Дата последнего сохранения: " + lastSaveTimeString + "\n";
        
        return new Response(getId(), ResponseType.SUCCESS, PrintType.LINE, result);
    }

    /**
     * Processes the provided request and delegates it to the appropriate command handler.
     *
     * @param request The {@link Request} to be processed.
     * @return A {@link Response} representing the outcome of the request processing.
     */
    @Override
    public Response proceedRequest(Request request) {
        if (request.getType() == RequestType.EXECUTE_COMMAND) {
            lastResponse = executeCommand(request);
            return lastResponse;
        }

        return new Response(getId(), ResponseType.SUCCESS, PrintType.WARNING, "Not correct request type");
    }


    /**
     * The Factory class provides methods to create instances of the Info command
     * and describe its functionality.
     */
    public static class Factory implements ICommandFactory {
        
        /**
         * Creates a new instance of the Info command.
         *
         * @param id               The unique identifier for the command.
         * @param arguments        The initial arguments provided to the command (not used).
         * @param commandControl   The {@link CommandControl} instance for managing commands.
         * @param collectionControl The {@link CollectionControl} instance for managing the collection.
         * @return A new instance of the Info command.
         */
        @Override
        public ICommand create(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl, Request request) {
            return new Info(id, arguments, commandControl, collectionControl);
        }

        /**
         * Returns a brief description of the Info command.
         *
         * @return A short description of the command functionality.
         */
        @Override
        public String getDescription() {
            return "info: вывести информацию о коллекции";
        }

        /**
         * Returns an extended description of the Info command, providing more details about its purpose.
         *
         * @return A detailed description of the command functionality.
         */
        @Override
        public String getExtendedDescription() {
            return "info: вывести информацию о коллекции.";
        }
    }
}
