package commands;

import connections.PrintType;
import connections.Request;
import connections.RequestType;
import connections.Response;
import connections.ResponseType;
import connections.ServerRequest;
import connections.ServerResponse;
import controls.CollectionControl;
import controls.CommandControl;
import models.Flat;
import util.StringWrapper;

/**
 * The MaxByCreationDate class implements the {@link ICommand} interface and provides functionality
 * to find and display a flat from the collection whose creation date is the latest.
 */
public class MaxByCreationDate implements ICommand{
    
    /**
     * The unique identifier of the command.
     */
    private int id;

    /**
     * The {@link CommandControl} instance for managing command-related operations.
     */
    private CommandControl commandControl;

    /**
     * The {@link CollectionControl} instance for managing the collection of flats.
     */
    private CollectionControl collectionControl;

    /**
     * The last {@link Response} generated during the command execution.
     */
    private Response lastResponse;


    /**
     * Constructs a new MaxByCreationDate command.
     *
     * @param id               The unique identifier for this command.
     * @param arguments        The initial arguments provided to the command (not used).
     * @param commandControl   The {@link CommandControl} instance for managing commands.
     * @param collectionControl The {@link CollectionControl} instance for managing the collection.
     */
    public MaxByCreationDate(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl) {
        super();
        
        this.id = id;
        this.commandControl = commandControl;
        this.collectionControl = collectionControl;
        proceedRequest(new Request(id, RequestType.EXECUTE_COMMAND, arguments));
    }


    /**
     * Returns the unique identifier of the command.
     *
     * @return The command ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the {@link CommandControl} instance associated with this command.
     *
     * @return The {@link CommandControl} instance.
     */
    public CommandControl getCommandControl() {
        return commandControl;
    }

    /**
     * Returns the {@link CollectionControl} instance associated with this command.
     *
     * @return The {@link CollectionControl} instance.
     */
    public CollectionControl getCollectionControl() {
        return collectionControl;
    }

    /**
     * Returns the last {@link Response} generated by this command.
     *
     * @return The last {@link Response}.
     */
    public Response getLastResponse() {
        return lastResponse;
    }


    /**
     * Executes the command by finding the flat with the latest creation date in the collection.
     * If the collection is empty, a warning response is returned.
     *
     * @param request The {@link Request} object containing the command details.
     * @return A {@link Response} object with either the details of the flat with the latest creation
     *         date or a message indicating that the collection is empty.
     */
    private Response executeCommand(Request request) {
        Flat maxFlat = collectionControl.maxByCreationDate();
        if (request instanceof ServerRequest) {
            ServerRequest req = (ServerRequest) request;
            if (maxFlat == null) return new ServerResponse(req.getClientCommandId(), ResponseType.INVALID_REQUEST, PrintType.LINE, new StringWrapper("no_data"), req.getClientId());
            return new ServerResponse(req.getClientCommandId(), ResponseType.SUCCESS, PrintType.LINE, maxFlat, req.getClientId());
        }
        if (maxFlat == null) return new Response(getId(), ResponseType.SUCCESS, PrintType.WARNING, "Коллекция пуста.");
        return new Response(getId(), ResponseType.SUCCESS, PrintType.LINE, maxFlat.toString());
    }

    /**
     * Processes the provided request and delegates it to the appropriate command handler.
     *
     * @param request The {@link Request} to be processed.
     * @return A {@link Response} representing the outcome of the request processing.
     */
    @Override
    public Response proceedRequest(Request request) {
        if (request.getType() == RequestType.EXECUTE_COMMAND) {
            lastResponse = executeCommand(request);
            return lastResponse;
        }

        return new Response(getId(), ResponseType.SUCCESS, PrintType.WARNING, "Not correct request type");
    }


    /**
     * The Factory class provides methods to create instances of the MaxByCreationDate command
     * and describe its functionality.
     */
    public static class Factory implements ICommandFactory {

        /**
         * Creates a new instance of the MaxByCreationDate command.
         *
         * @param id               The unique identifier for the command.
         * @param arguments        The initial arguments provided to the command (not used).
         * @param commandControl   The {@link CommandControl} instance for managing commands.
         * @param collectionControl The {@link CollectionControl} instance for managing the collection.
         * @return A new instance of the MaxByCreationDate command.
         */
        @Override
        public ICommand create(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl, Request request) {
            return new MaxByCreationDate(id, arguments, commandControl, collectionControl);
        }

        /**
         * Returns a brief description of the MaxByCreationDate command.
         *
         * @return A short description of the command functionality.
         */
        @Override
        public String getDescription() {
            return "max_by_creation_date: вывести любую квартиру коллекции, значение поля creationDate которой является максимальным";
        }

        /**
         * Returns an extended description of the MaxByCreationDate command, detailing its behavior.
         *
         * @return A detailed description of the command functionality.
         */
        @Override
        public String getExtendedDescription() {
            return "max_by_creation_date: вывести любую квартиру коллекции, значение поля creationDate которой является максимальным.";
        }
    }
}
