package commands;

import connections.PrintType;
import connections.Request;
import connections.RequestType;
import connections.Response;
import connections.ResponseType;
import connections.ServerRequest;
import connections.ServerResponse;
import controls.CollectionControl;
import controls.CommandControl;
import controls.flat_builder.FlatBuilderAdd;
import controls.flat_builder.IBuilder;
import models.Flat;
import util.LongWrapper;

/**
 * The RemoveLower class implements the {@link ICommand} interface and provides functionality
 * to remove all flats from the collection whose area is smaller than the specified area or a given flat.
 */
public class RemoveLower implements ICommand{

    /**
     * The unique identifier of the command.
     */
    private int id;

    /**
     * The {@link CommandControl} instance for managing command-related operations.
     */
    private CommandControl commandControl;

    /**
     * The {@link CollectionControl} instance for managing the collection of flats.
     */
    private CollectionControl collectionControl;

    /**
     * The last {@link Response} generated during the command execution.
     */
    private Response lastResponse;

    /**
     * The {@link IBuilder} instance used for constructing {@link Flat} objects.
     */
    private IBuilder builder;


    /**
     * Constructs a new RemoveLower command.
     *
     * @param id               The unique identifier for this command.
     * @param arguments        The initial arguments specifying the area or flat (required).
     * @param commandControl   The {@link CommandControl} instance for managing commands.
     * @param collectionControl The {@link CollectionControl} instance for managing the collection.
     */
    public RemoveLower(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl) {
        super();
        
        this.id = id;
        this.commandControl = commandControl;
        this.collectionControl = collectionControl;
        builder = new FlatBuilderAdd(collectionControl);
        proceedRequest(new Request(id, RequestType.EXECUTE_COMMAND, arguments));
    }


    /**
     * Returns the unique identifier of the command.
     *
     * @return The command ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the {@link CommandControl} instance associated with this command.
     *
     * @return The {@link CommandControl} instance.
     */
    public CommandControl getCommandControl() {
        return commandControl;
    }

    /**
     * Returns the {@link CollectionControl} instance associated with this command.
     *
     * @return The {@link CollectionControl} instance.
     */
    public CollectionControl getCollectionControl() {
        return collectionControl;
    }

    /**
     * Returns the last {@link Response} generated by this command.
     *
     * @return The last {@link Response}.
     */
    public Response getLastResponse() {
        return lastResponse;
    }


    /**
     * Executes the command to remove flats from the collection whose area is smaller than
     * the specified flat or area. If the area or flat details are invalid, an error response is returned.
     *
     * @param request The {@link Request} object containing the command details.
     * @return A {@link Response} indicating the outcome of the removal operation.
     */
    private Response executeCommand(Request request) {
        if (request instanceof ServerRequest) {
            ServerRequest req = (ServerRequest) request;
            builder = (IBuilder) req.getContentExt();
            builder.setCollection(collectionControl);
            Flat flat = builder.build();
            long count = collectionControl.removeLower(flat, req.getUser().getName());
            return new ServerResponse(req.getClientCommandId(), ResponseType.SUCCESS, PrintType.LINE, new LongWrapper(count), req.getClientId());
        }


        if (request.getType() == RequestType.EXECUTE_COMMAND) {
            if (request.getContent() == null) return new Response(getId(), ResponseType.REQUEST_VALUES, PrintType.LINE, "Задайте квартиру", builder.getPrompt());
            builder.setValue("null flat");
            builder.setValue("3");
            builder.setValue("3");
            Response r = builder.setValue(request.getContent());
            if (r.getType() == ResponseType.SUCCESS) {
                Flat flat = builder.build();
                long count = collectionControl.removeLower(flat, "ADMIN");
                return new Response(getId(), ResponseType.SUCCESS, PrintType.LINE, "Удалены все квартиры меньшие данной площади: " + count + " штук");
            }
            return new Response(getId(), ResponseType.INVALID_ARGUMENT, PrintType.ERROR, "Неверный формат задания площади");
        }
        
        Response resp = builder.setValue(request.getContent());
        String prompt = builder.getPrompt();
        if (resp.getType() == ResponseType.SUCCESS) {
            if (prompt != null) return new Response(getId(), ResponseType.REQUEST_VALUES, PrintType.NONE, resp.getContent(), prompt);
            else {
                Flat flat = builder.build();
                long count = collectionControl.removeLower(flat, "ADMIN");
                return new Response(getId(), ResponseType.SUCCESS, PrintType.LINE, "Удалены все квартиры, площадью меньше " + request.getContent() + ": " + count + " штук");
            }
        }
        return new Response(getId(), resp.getType(), resp.getPrintType(), resp.getContent(), prompt);
    }
    
    /**
     * Processes the provided request and delegates it to the appropriate command handler.
     *
     * @param request The {@link Request} to be processed.
     * @return A {@link Response} representing the outcome of the request processing.
     */
    @Override
    public Response proceedRequest(Request request) {
        if (request.getType() == RequestType.EXECUTE_COMMAND || request.getType() == RequestType.PROCEED_COMMAND) {
            lastResponse = executeCommand(request);
            return lastResponse;
        }

        return new Response(getId(), ResponseType.SUCCESS, PrintType.WARNING, "Not correct request type");
    }


    /**
     * The Factory class provides methods to create instances of the RemoveLower command
     * and describe its functionality.
     */
    public static class Factory implements ICommandFactory {

        /**
         * Creates a new instance of the RemoveLower command.
         *
         * @param id               The unique identifier for the command.
         * @param arguments        The initial arguments specifying the area or flat (required).
         * @param commandControl   The {@link CommandControl} instance for managing commands.
         * @param collectionControl The {@link CollectionControl} instance for managing the collection.
         * @return A new instance of the RemoveLower command.
         */
        @Override
        public ICommand create(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl, Request request) {
            return new RemoveLower(id, arguments, commandControl, collectionControl);
        }

        /**
         * Returns a brief description of the RemoveLower command.
         *
         * @return A short description of the command functionality.
         */
        @Override
        public String getDescription() {
            return "remove_lower area / {flat}: удалить из коллекции все квартиры, меньшие заданной по площади";
        }

        /**
         * Returns an extended description of the RemoveLower command, providing details
         * about its functionality and requirements.
         *
         * @return A detailed description of the command functionality.
         */
        @Override
        public String getExtendedDescription() {
            return "remove_lower {flat}: удалить из коллекции все квартиры, меньшие заданной по площади. Необходимые значения для flat будут запрошены в последующих строчках.\nremove_lower area: удалить из коллекции все квартиры, площадь которых, меньше area.";
        }
    }
}
