package commands;

import connections.PrintType;
import connections.Request;
import connections.RequestType;
import connections.Response;
import connections.ResponseType;
import connections.ServerRequest;
import connections.ServerResponse;
import controls.CollectionControl;
import controls.CommandControl;
import controls.flat_builder.FlatBuilderUpdate;
import controls.flat_builder.IBuilder;
import models.Flat;
import util.StringWrapper;

/**
 * The Update class implements the {@link ICommand} interface and provides functionality
 * to update the details of an existing flat in the collection based on its unique identifier.
 */
public class Update implements ICommand{

    /**
     * The unique identifier of the command.
     */
    private int id;

    /**
     * The {@link CommandControl} instance for managing command-related operations.
     */
    private CommandControl commandControl;

    /**
     * The {@link CollectionControl} instance for managing the collection of flats.
     */
    private CollectionControl collectionControl;

    /**
     * The last {@link Response} generated during the command execution.
     */
    private Response lastResponse;

    /**
     * The {@link IBuilder} instance used for updating {@link Flat} objects.
     */
    private IBuilder builder;


    /**
     * Constructs a new Update command.
     *
     * @param id               The unique identifier for this command.
     * @param arguments        The initial arguments specifying the flat ID (required).
     * @param commandControl   The {@link CommandControl} instance for managing commands.
     * @param collectionControl The {@link CollectionControl} instance for managing the collection.
     */
    public Update(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl) {
        super();
        
        this.id = id;
        this.commandControl = commandControl;
        this.collectionControl = collectionControl;
        proceedRequest(new Request(id, RequestType.EXECUTE_COMMAND, arguments));
    }


    /**
     * Returns the unique identifier of the command.
     *
     * @return The command ID.
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the {@link CommandControl} instance associated with this command.
     *
     * @return The {@link CommandControl} instance.
     */
    public CommandControl getCommandControl() {
        return commandControl;
    }

    /**
     * Returns the {@link CollectionControl} instance associated with this command.
     *
     * @return The {@link CollectionControl} instance.
     */
    public CollectionControl getCollectionControl() {
        return collectionControl;
    }

    /**
     * Returns the last {@link Response} generated by this command.
     *
     * @return The last {@link Response}.
     */
    public Response getLastResponse() {
        return lastResponse;
    }


    /**
     * Executes the command to update the details of a flat in the collection.
     * Prompts for new values to update the flat and validates the inputs.
     *
     * @param request The {@link Request} object containing the command details.
     * @return A {@link Response} representing the result of the update operation or prompts for input.
     */
    private Response executeCommand(Request request) {
        if (request instanceof ServerRequest) {
            ServerRequest req = (ServerRequest) request;
            builder = (FlatBuilderUpdate) req.getContentExt();
            builder.setCollection(collectionControl);
            Flat flat = builder.build();
            if (collectionControl.update(flat, req.getUser().getName())) return new ServerResponse(req.getClientCommandId(), ResponseType.SUCCESS, PrintType.LINE, flat, req.getClientId());
            else return new ServerResponse(req.getClientCommandId(), ResponseType.VALIDATION_FAILURE, PrintType.LINE, new StringWrapper(""), req.getClientId());
        }

        
        if (request.getType() == RequestType.EXECUTE_COMMAND) {
            if (request.getContent() == null) return new Response(getId(), ResponseType.INVALID_ARGUMENT, PrintType.ERROR, "Команда update id в обязательном порядке принимает аргумент id.\nЧто бы узнать про команды подробнее, введите help.");
            builder = new FlatBuilderUpdate(collectionControl);
            Response resp = builder.setValue(request.getContent());
            if (resp.getType() != ResponseType.SUCCESS) return new Response(getId(), resp.getType(), resp.getPrintType(), resp.getContent());
            return new Response(getId(), ResponseType.REQUEST_VALUES, PrintType.LINE, "Введите новые значения для квартиры. Было:\n" + resp.getContent(), builder.getPrompt());
        }
        
        Response resp = builder.setValue(request.getContent());
        String prompt = builder.getPrompt();
        if (resp.getType() == ResponseType.SUCCESS) {
            if (prompt != null) return new Response(getId(), ResponseType.REQUEST_VALUES, PrintType.NONE, resp.getContent(), prompt);
            else {
                Flat flat = builder.build();
                if (collectionControl.update(flat, "ADMIN")) return new Response(getId(), ResponseType.SUCCESS, PrintType.LINE, "Квартира успешно обновлена:\n" + flat.toString());
                else return new Response(getId(), ResponseType.VALIDATION_FAILURE, PrintType.LINE, "Не удалось обновить квартиру");
            }
        }
        return new Response(getId(), resp.getType(), resp.getPrintType(), resp.getContent(), prompt);
    }

    /**
     * Processes the provided request and delegates it to the appropriate command handler.
     *
     * @param request The {@link Request} to be processed.
     * @return A {@link Response} representing the outcome of the request processing.
     */
    @Override
    public Response proceedRequest(Request request) {
        if (request.getType() == RequestType.EXECUTE_COMMAND || request.getType() == RequestType.PROCEED_COMMAND) {
            lastResponse = executeCommand(request);
            return lastResponse;
        }

        return new Response(getId(), ResponseType.SUCCESS, PrintType.WARNING, "Not correct request type");
    }


    /**
     * The Factory class provides methods to create instances of the Update command
     * and describe its functionality.
     */
    public static class Factory implements ICommandFactory {

        /**
         * Creates a new instance of the Update command.
         *
         * @param id               The unique identifier for the command.
         * @param arguments        The initial arguments specifying the flat ID.
         * @param commandControl   The {@link CommandControl} instance for managing commands.
         * @param collectionControl The {@link CollectionControl} instance for managing the collection.
         * @return A new instance of the Update command.
         */
        @Override
        public ICommand create(int id, String arguments, CommandControl commandControl, CollectionControl collectionControl, Request request) {
            return new Update(id, arguments, commandControl, collectionControl);
        }

        /**
         * Returns a brief description of the Update command.
         *
         * @return A short description of the command functionality.
         */
        @Override
        public String getDescription() {
            return "update id {flat} обновить значения квартиры, id которой равен id";
        }

        /**
         * Returns an extended description of the Update command, providing details
         * about its functionality and required inputs.
         *
         * @return A detailed description of the command functionality.
         */
        @Override
        public String getExtendedDescription() {
            return "update id {flat} обновить значения квартиры, id которой равен id.\nНеобходимые значения для flat будут запрошены в последующих строчках.";
        }
    }
}
